### ISSUE TITLE
Support 5.5+ Laravel

### ISSUE THREAD

**Issue by daaner** [diglactic/laravel-breadcrumbs#3]
why did you remove support for laravel 5.5-5.8? nothing has changed globally since the fork.
If I return, accept the PR?

**Comment by shengslogar** [comment]
Hi @daaner,

This was intentional. Laravel 5.x is no longer officially supported (see [here](https://laravel.com/docs/6.x/releases#support-policy)) and I'd like to move the code base to more modern PHP syntax.

If you have a project that runs on Laravel 5, I'd strongly suggest you upgrade it, but you can use [Dave's original fork](https://github.com/davejamesmiller/laravel-breadcrumbs) in the meantime.

SS

**Comment by daaner** [comment]
I have a OpenSource project in support that is supported from 5.5 to 8+ and there is a Dave package. I would like to update to yours, but due to limitations in the composer I am unable to do this

**Comment by daaner** [comment]
https://github.com/LaravelRUS/SleepingOwlAdmin/blob/development/composer.json#L42

**Comment by shengslogar** [comment]
Please read my previous comment. I would strongly suggest moving your own project away from Laravel 5.x, but I do not want to introduce any legacy compatibility into this project. If you really need to support Laravel 5.x, you're more than welcome to create your own fork.
