### ISSUE TITLE
Removed support for boostrap 3

### ISSUE THREAD

**Issue by lasseeee** [diglactic/laravel-breadcrumbs#34]
Crashed an app due to removal of Boostrap 3 support. Support should either be kept, or removal marked as a breaking change. Config still lists (sadly) removed view options.

**Comment by ShengSlogar** [comment]
Thanks for pointing this out.

v7 had a number of breaking changes, including the removal of now EOL Bootstrap v2 and v3 templates. I failed to mention this in the upgrade guide. Will add that in shortly. Here's that commit for reference: https://github.com/diglactic/laravel-breadcrumbs/commit/2aeacfaa33f3b13400be0bdf3bb2357f7b78548c

Since we follow [Semantic Versioning](https://semver.org/), you should always expect breaking changes whenever a major version is released.

**Comment by ShengSlogar** [comment]
Closing with https://github.com/diglactic/laravel-breadcrumbs/commit/0a14e8785fa9423c878edd3975af2a92dfcdaf42
