### ISSUE TITLE
Use in Vue

### ISSUE THREAD

**Issue by abbasmashaddy72** [diglactic/laravel-breadcrumbs#37]
Hi,

I want to use this package in Vue with Inertia JS.

Can please explain how can I use it.
@ShengSlogar

**Comment by ShengSlogar** [comment]
Hmm, I haven't used nor recommend using this package with Inertia.js, but the easiest way I can think would be passing the results of `Breadcrumbs::render()` to every route, following Inertia's shared-data pattern, and directly outputting that raw HTML inside your Vue.js templates.

https://inertiajs.com/shared-data

A better approach might be tapping into `Breadcrumbs::generate()`, but you'd have to parse those results and recreate our Blade templates inside Vue.js, greatly reducing the point of using this package in the first place.

https://github.com/diglactic/laravel-breadcrumbs/blob/c7982362ff5b601f1f58601e486f54a94278bac1/src/Manager.php#L126-L158

https://github.com/diglactic/laravel-breadcrumbs/blob/0a14e8785fa9423c878edd3975af2a92dfcdaf42/resources/views/tailwind.blade.php

**Comment by beard7** [comment]
It turns out that this is very simple, and if you're migrating an excisting app to Inertia and Vue, as I am, it's also very useful.

@shengslogar basically answered the question above, but I can confirm it's as simple as adding `'breadcrumbs' => fn () => Breadcrumbs::generate()` to your HandleInertiaRequests middleware to include an array of breadcrumbs in the shared data of each page.

**Comment by shengslogar** [comment]
@beard7 I can also recommend [`RobertBoes/inertia-breadcrumbs`](https://github.com/RobertBoes/inertia-breadcrumbs)!
