### ISSUE TITLE
Breadcrumb not found with name "projects.tasks.index"

### ISSUE THREAD

**Issue by precamp-io** [diglactic/laravel-breadcrumbs#51]
sorry for the bother again I am quiet new to Laravel and just started using vs 8, I have studied routing in quiet a bit of detail to try to wrap my head around it but not getting it, please can you tell me what I am doing wrong here:

This is my route and it currently working without the breadcrumb.
`Route::get('/projects/{pid}/task',['as' => 'projects.tasks.index','uses' =>'ProjectTaskController@index'])->middleware(['auth','XSS']);`

This is breadcrumb routes/breadcrumbs.php
```
Breadcrumbs::for('projects.tasks.index', function (BreadcrumbTrail $trail, ProjectTask $task) {
    $trail->parent('projects.index');
    $trail->push($task->title, route('projects', $task));
});
```

The error i am getting is:
Argument 2 passed to Diglactic\Breadcrumbs\ServiceProvider::{closure}() must be an instance of App\Models\ProjectTask, string given, called in C:\wamp64\www\precampDev5_v1\vendor\diglactic\laravel-breadcrumbs\src\Generator.php on line 64 (View: C:\wamp64\www\precampDev5_v1\resources\views\tasks\index.blade.php)

**Comment by shengslogar** [comment]
You'll want to read up on [route-model binding](https://laravel.com/docs/9.x/routing#route-model-binding). Laravel will resolve models where parameters in functions match their named route variable.

In other words, for `ProjectTask $task,` you would need route `/projects/{project_task}` to match. Because Laravel can't match that, it's not converting the input (string) to a model (ProjectTask), hence your exception.
