### ISSUE TITLE
generate() multiple times with null name return model binding only first time

### ISSUE THREAD

**Issue by Morry981** [diglactic/laravel-breadcrumbs#69]
Hi, i found in my projects this issue using in the same page both
`{{ Breadcrumbs::render() }}` (needed for json microdata) and `{{ Breadcrumbs::generate() }}` (needed for my graphic layout)

For example:
`https://website.tld/books/book-1`
in `web.php`
```php
Route::get('/books/{books:slug}', 'view')->name('books.book');
```

It is comfortable to not pass any parameters like route name and model 
so the first `render()` returns **the correct `Book` model instance** to
```php
Breadcrumbs::for('books.book', function (BreadcrumbTrail $trail, Model|string $book) {
    $trail->parent('books.index');
    $trail->push($book->name, route('books.book', $book))
});
```
**but in `generate()` returns as string "`book-1`"**

The same happens if i **invert** them or i **add other render() functions** (of course not needed)

I've already tried to just add a simple cache system to line 135 of Manager class
```php
private ?array $cacheNullRoute = null;
public function generate(?string $name = null, ...$params): Collection
{
    $origName = $name;

    // Route-bound breadcrumbs
    if ($name === null) {
        try {
            [$name, $params] = $this->getCurrentRoute();
            // FIX: remember $params
            if (isset($this->cacheNullRoute[$name])) {
                [$name, $params] = $this->cacheNullRoute[$name];
            } else $this->cacheNullRoute[$name] = [$name, $params];
        } catch (UnnamedRouteException $e) {
	    // continue
```

That work fine to solve the problem so if you don't find out any problems in that or i'm not missing something
i can make a PR.
Let me know!

PS. of course i always worked around the problem passing the correct params to generate()
but i want to know if i can solve it easily

**Comment by shengslogar** [comment]
I wasn't able to repro this with a similar setup. I assume in this line:

```
Route::get('/books/{books:slug}', 'view')
```

`view` points to a controller. Without seeing what's in your controller, I can't be entirely sure what's happening, but I would bet the problem is hidden somewhere in there. Here was my unsuccessful attempt to repro:

### routes/web.php
```
Route::get('users/{user:email}', [UserController::class, 'show'])->name('users.show');
```

### routes/breadcrumbs.php
```
<?php

use Diglactic\Breadcrumbs\Breadcrumbs;
use Diglactic\Breadcrumbs\Generator as BreadcrumbTrail;
use Illuminate\Database\Eloquent\Model;

// Even type-hinting `Model|string` didn't throw route-model binding off here
Breadcrumbs::for('users.show', function (BreadcrumbTrail $trail, Model|string $user) {
    $trail->push($user->name, 'example.com');
});
```

### views/user-show.blade.php
```
{{ Breadcrumbs::render() }}

{{ Breadcrumbs::generate() }}
```

### app/Http/Controllers/UserController.php
```
<?php

namespace App\Http\Controllers;

use App\Models\User;

class UserController extends Controller
{
    public function show(User $user)
    {
        return \view('user-show');
    }
}
```

### HTTP result

<img width="723" alt="Screenshot of successful web request with the following content: 1. Dagmar Hoeger [{&quot;title&quot;:&quot;Dagmar Hoeger&quot;,&quot;url&quot;:&quot;example.com&quot;}]" src="https://github.com/diglactic/laravel-breadcrumbs/assets/4350009/21afdfd5-eca2-405c-b236-d429856e0a3c">

Feel free to reopen if you determine there is something specifically broken inside this package that is unrelated to your code.
